import Footer from './components/Footer'
import Navbar from './components/Navbar'
import './globals.css'
import { Inter, Roboto } from 'next/font/google'

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
})
 
export const metadata = {
  title: 'Showkatul islam',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
      <main className="flex min-h-screen flex-col bg-[#121212] text-zinc-200">
        <Navbar/>
        {children}
        <Footer/>
       </main>  
      </body>
    </html>
  )
}
